import { StatKey } from "./PokemonStats";

export enum Natures {
  Hardy = "Hardy",
  Lonely = "Lonely",
  Brave = "Brave",
  Adamant = "Adamant",
  Naughty = "Naughty",
  Bold = "Bold",
  Docile = "Docile",
  Relaxed = "Relaxed",
  Impish = "Impish",
  Lax = "Lax",
  Timid = "Timid",
  Hasty = "Hasty",
  Serious = "Serious",
  Jolly = "Jolly",
  Naive = "Naive",
  Modest = "Modest",
  Mild = "Mild",
  Quiet = "Quiet",
  Bashful = "Bashful",
  Rash = "Rash",
  Calm = "Calm",
  Gentle = "Gentle",
  Sassy = "Sassy",
  Careful = "Careful",
  Quirky = "Quirky",
}

export type NatureModifier = Omit<
  {
    [key in StatKey]: number;
  },
  StatKey.health
>;

export const NatureEffect: Record<Natures, NatureModifier> = {
  Hardy: {
    attack: 1,
    defense: 1,
    specialAttack: 1,
    specialDefense: 1,
    speed: 1,
  },
  Lonely: {
    attack: 1.1,
    defense: 0.9,
    specialAttack: 1,
    specialDefense: 1,
    speed: 1,
  },
  Brave: {
    attack: 1.1,
    defense: 1,
    specialAttack: 1,
    specialDefense: 1,
    speed: 0.9,
  },
  Adamant: {
    attack: 1.1,
    defense: 1,
    specialAttack: 0.9,
    specialDefense: 1,
    speed: 1,
  },
  Naughty: {
    attack: 1.1,
    defense: 1,
    specialAttack: 1,
    specialDefense: 0.9,
    speed: 1,
  },
  Bold: {
    attack: 0.9,
    defense: 1.1,
    specialAttack: 1,
    specialDefense: 1,
    speed: 1,
  },
  Docile: {
    attack: 1,
    defense: 1,
    specialAttack: 1,
    specialDefense: 1,
    speed: 1,
  },
  Relaxed: {
    attack: 1,
    defense: 1.1,
    specialAttack: 1,
    specialDefense: 1,
    speed: 0.9,
  },
  Impish: {
    attack: 1,
    defense: 1.1,
    specialAttack: 0.9,
    specialDefense: 1,
    speed: 1,
  },
  Lax: {
    attack: 1,
    defense: 1.1,
    specialAttack: 1,
    specialDefense: 0.9,
    speed: 1,
  },
  Timid: {
    attack: 0.9,
    defense: 1,
    specialAttack: 1,
    specialDefense: 1,
    speed: 1.1,
  },
  Hasty: {
    attack: 1,
    defense: 0.9,
    specialAttack: 1,
    specialDefense: 1,
    speed: 1.1,
  },
  Serious: {
    attack: 1,
    defense: 1,
    specialAttack: 1,
    specialDefense: 1,
    speed: 1,
  },
  Jolly: {
    attack: 1,
    defense: 1,
    specialAttack: 0.9,
    specialDefense: 1,
    speed: 1.1,
  },
  Naive: {
    attack: 1,
    defense: 1,
    specialAttack: 1,
    specialDefense: 0.9,
    speed: 1.1,
  },
  Modest: {
    attack: 0.9,
    defense: 1,
    specialAttack: 1.1,
    specialDefense: 1,
    speed: 1,
  },
  Mild: {
    attack: 1,
    defense: 0.9,
    specialAttack: 1.1,
    specialDefense: 1,
    speed: 1,
  },
  Quiet: {
    attack: 1,
    defense: 1,
    specialAttack: 1.1,
    specialDefense: 1,
    speed: 0.9,
  },
  Bashful: {
    attack: 1,
    defense: 1,
    specialAttack: 1,
    specialDefense: 1,
    speed: 1,
  },
  Rash: {
    attack: 1,
    defense: 1,
    specialAttack: 1.1,
    specialDefense: 0.9,
    speed: 1,
  },
  Calm: {
    attack: 0.9,
    defense: 1,
    specialAttack: 1,
    specialDefense: 1.1,
    speed: 1,
  },
  Gentle: {
    attack: 1,
    defense: 0.9,
    specialAttack: 1,
    specialDefense: 1.1,
    speed: 1,
  },
  Sassy: {
    attack: 1,
    defense: 1,
    specialAttack: 1,
    specialDefense: 1.1,
    speed: 0.9,
  },
  Careful: {
    attack: 1,
    defense: 1,
    specialAttack: 0.9,
    specialDefense: 1.1,
    speed: 1,
  },
  Quirky: {
    attack: 1,
    defense: 1,
    specialAttack: 1,
    specialDefense: 1,
    speed: 1,
  },
};
